### PR TITLE
Establish a default command for all SpartronicsSubsystems for diagnosic.

### PR DESCRIPTION
**Pull request by dbadb**
Subclasses should establish their default command in their constructor.

### CODE REVIEW

**Comment by omentic** [comment]
Dana, what is the point in doing this over [what we currently have?](https://github.com/Spartronics4915/2020-InfiniteRecharge/blob/fbf48e91017504bc9dd7450a741f4d282cc23172/src/main/java/com/spartronics4915/frc2020/RobotContainer.java#L102)

**Comment by dbadb** [comment]
We should leave it up to each subsystem to express what the default command would be and we should have a concrete name for each command running on a subsystem.  We are posting to the smartdashboard what the current command is running on each subsystem and this theoretically will help us to diagnose problems with subsystem contention, etc.

Note that you are missing Indexer and LED  in RobotContainer and that's a symptom, I figure, of this missing formalism/structure in Subsystem design and encapsulation.  Also note that the RunCommand shows up in the dashboard as "RunCommand" which isn't very helpful in diagnosing what's going on.

**Comment by omentic** [comment]
@dbadb I would prefer to keep setting the default command something done in RobotContainer. Having Command logic hidden away in subsystems seems like it will be a pain to work with / debug. 

LED is missing bling states (which doesn't make a default command very helpful). The indexer's current PR will need to include one, as well as construct itself in RobotContainer.

**Comment by dbadb** [comment]
@j-james -  your call, but please don't underestimate the value of encapsulation.  (trust the force - ;o))
The pitch:  we don't want git contention over these lines of code.  Should a subsystem decide that it wants to tweak the implementation, provide logging, etc I claim that the owner of RobotContainer shouldn't be bothered, that it's really a private issue for subsystems - "what do you want to do when you're doing nothing".  Perhaps the compromise would be to require that all SubsystemCommands include a command named DefaultCommand.

**Comment by binnur** [comment]
> LED is missing bling states (which doesn't make a default command very helpful). 

In general I don't see a default command for LED useful. Default command runs periodically, and LED is event driven -- similar to Joystick. It just sits there and waits for events to act on -- there is no reason to keep writing the same bling state (Arduino takes care of that) and we shouldn't be changing the existing animation to what LED subsystem thinks it should be. I put in a dashboard logging activity in the default command, but that could easily move into the method where the writes/bling state change occurs. 

I don't have a strong opinion on either process (RobotContainer vs subsystems) for hosting the default command, as long as it is consistent across the board.

**Comment by dbadb** [comment]
In a way - this underscores my (fairly nitpicky) point.  The implementation
of a default command is part of the inner-working of a subsystem.  I
wouldn't expect the maintainer of RobotContainer to need to have to know
that Bling needs or doesn't need a default command.  It's an implementation
detail.  We definitely agree that uniformity is good and I recall lots of
confusion among new robot programmers regarding the functionality of the
command scheduler.  If LED had a default command called Asleep, it would
clearly express in the network tables something about its state (and I
highly doubt that a Sleep command would represent computational burden).

At the end of the day I just suspect it may be helpful to be able to go to
one place to understand the current state of every subsystem.  This is the
intent behind SpartronicsSubsystem's reporting in its periodic method.

**Pull request merged**
