### PR TITLE
Add a formatter

### PR DESCRIPTION
**Pull request by omentic**
#39 

I generated this XML file from Eclipse's formatting settings - doesn't work yet, and I need to find out why...

https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

### CODE REVIEW

**Comment by binnur** [comment]
Did you set the formatter URL and enabled formatting controls in VSCode? 
See [setting formatter URL](https://stackoverflow.com/questions/46030629/need-to-import-eclipse-java-formatter-profile-in-visual-studio-code) and [setting formatter options for java.format.*](https://marketplace.visualstudio.com/items?itemName=redhat.java). With these changes, my vscode build is updating the code w/ format requirements.

Note -- we should push the format update requirements to the clients/programmers, and enforce it during our builds. If the formatting is not set right, the PR should fail.

**Comment by omentic** [comment]
@binnur I did, those are in the `.vscode` folder. But it seems like _our_ formatting settings aren't being run - ex. setting `org.eclipse.jdt.core.formatter.indentation.size` from `4` to `2` doesn't change anything on my end.

**Comment by binnur** [comment]
Try setting `java.format.enabled` to true

**Comment by omentic** [comment]
No change :confused:

**Comment by binnur** [comment]
Here is my settings file, which applies the format changes. I verified that if `java.format.enabled: false` will NOT apply format settings. Note that the workspace settings is only applied when project is opened. I also noted some issue w/ settings getting written over as 'false' when I initially tested it. Good luck!

PS. I am also using the extension 'Language Support for Java by Red Hat'.

```sh
}((2646e23...)) binnur@Moya(.vscode)> cat settings.json
{
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.format.settings.url": ".vscode/spartronics-formatter.xml",
    "java.format.settings.profile": "Spartronics",
    "java.format.enabled": true,
    "editor.formatOnSave": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "bin/": true,
        "**/.classpath": true,
        "**/.github": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    }
```

**Comment by dbadb** [comment]
https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html

may be a useful tool for defining multiple classes in a single file.

another might be simply nested classes.

**Comment by dbadb** [comment]
https://code.visualstudio.com/docs/getstarted/settings
https://code.visualstudio.com/docs/editor/multi-root-workspaces

Apparently .vscode/settings.json may not always be in force and this may have something to do with how you've created your vscode workspace.  In my case, when I changed workspace settings, they were stored in the workspace file itself (which isn't / shouldn't be stored in the repo since it contains machine/user-specific paths).   When I created a new workspace from scratch, I found that the formatter appears to work as long as I use a fully-qualified pathname, rather than a relative one.  I saw no error/warning when the system was unable to find the relative pathname.  This difference in behavior is discussed [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings).

To test this difference i used this URL for the "java.format.settings.url":

https://raw.githubusercontent.com/Spartronics4915/2017-STEAMworks/master/extra/Formatter.xml

I also set java.format.settings.profile to "Spartronics".

And just to be certain, I made sure to restart vscode after I'd changed the formatter.  Now each time i saved the file it reformatted.

Finally, of course, it's not ideal to require either a fully-qualified uri for these reasons:
1. we don't want to require internet access to edit files 
2. there is no hardcoded fully-qualified pathname that will work for all users.

According to https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings, we can embed formatting info in this file: .settings/org.eclipse.jdt.core.prefs.  The format of that file isn't xml so we can't use any existing formatter.  Here's an example: 

https://gist.github.com/fbricon/30c5971f7e492c8a74ca2b2d7a7bb966

And really finally:

I believe we want newlines before opening braces.  We adopted that convention a few years back when a student's bug associated with braces wasn't caught (being offscreen right) and it also didn't get caught by the compiler - since it was legal syntax.

**Comment by dbadb** [comment]
https://github.com/Spartronics4915/2020-InfiniteRecharge/pull/53

this approach seems to work for me.  If it works for Justice and for Binnur, I reckon it may work for all.

**Comment by dbadb** [comment]
2 questions: 
 Did the experiment fail?
 Did you know you could add my repo as another 'upstream' and pull directly from there?

**Comment by binnur** [comment]
I have 50-50 success. So, I need to dig into the info from @dbadb -- in both cases:
1. I fetched directly from Dana's repo
2. I started vscode using '$ code .'
In one laptop, code was reformatted on file save, on other nothing. I sync extensions between my systems. Once I am done w/ bling stuff, I will look at this again in more detail if not resolved by then.

**Comment by dbadb** [comment]
@Binnur: I'm guessing that on the machine it didn't work for, that there may be an override value in your .vscode/settings.json or in the actual workspace file (of type ".code-workspace")?

**Comment by omentic** [comment]
I see #53's been merged - sorry for not responding before then, I've been pretty held up with finals.

I got the XML file to work on my end, it seems like the setting I was using as a test (`org.eclipse.jdt.core.formatter.indentation.size`) doesn't actually apply on format regardless. Tested by editing a Gist of our 2017 formatter, and linking it to `.vscode/settings.json`. It works fine now (even locally), but if Binnur had issues, I agree a prefs file in `.settings` is the way to go. 

@dbadb Regarding the `org.eclipse.jdt.core.prefs` file - where did you get that from? There's a few settings in my `spartronics-formatter.xml` that I'd like to put in...

**Comment by binnur** [comment]
I chased down the problem to user settings that stated `"java.format.enabled" = false`. And, since I started vscode with `$ code .` and no workspace defined, I suspect this is what was overriding the formatting on the machine that did not work. fyi

**Comment by omentic** [comment]
@dbadb 
Differences from your file:

```
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_annotation=16
org.eclipse.jdt.core.formatter.alignment_for_enum_constants=16
org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_block_comment=true
org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_javadoc_comment=true
org.eclipse.jdt.core.formatter.comment.format_header=true
org.eclipse.jdt.core.formatter.comment.format_javadoc_comments=false
org.eclipse.jdt.core.formatter.comment.format_line_comments=true
org.eclipse.jdt.core.formatter.comment.indent_parameter_description=false
org.eclipse.jdt.core.formatter.indent_switchstatements_compare_to_switch=true
org.eclipse.jdt.core.formatter.insert_new_line_at_end_of_file_if_missing=insert
org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement=insert
org.eclipse.jdt.core.formatter.insert_new_line_before_else_in_if_statement=insert
org.eclipse.jdt.core.formatter.insert_new_line_before_finally_in_try_statement=insert
org.eclipse.jdt.core.formatter.insert_new_line_before_while_in_do_statement=insert
org.eclipse.jdt.core.formatter.insert_space_after_additive_operator=insert
org.eclipse.jdt.core.formatter.insert_space_after_opening_brace_in_array_initializer=do not insert
org.eclipse.jdt.core.formatter.insert_space_before_closing_brace_in_array_initializer=do not insert
org.eclipse.jdt.core.formatter.join_lines_in_comments=false
org.eclipse.jdt.core.formatter.use_on_off_tags=false
org.eclipse.jdt.core.formatter.wrap_before_bitwise_operator=true
```
\+ new settings

**Comment by dbadb** [comment]
org.eclipse.jdt.core.formatter.keep_lambda_body_block_on_one_line=one_line_always

we might want to relax this one?   I think multiline lambdas are viable.
propositions and squeezing them onto a single line sould be bad.

**Comment by binnur** [comment]
I agree on that, i.e. relaxing the one_line_always. Wish they had am auto-formatter that worked well for organizing lambda blocks for readability.

**Pull request merged**
