### PR TITLE
Integrate SpartronicsLib with this year's project.

### PR DESCRIPTION
**Pull request by dbadb**
Declan: please validate before merging.

Integrate Spartronics tests into this year's project. (A few tests still
fail).

Update Phoenix vendordep to latest and greatest.
Update WPI GradleRIO to latest and greatest.
Add support for build-tagging.

### CODE REVIEW

**Comment by dbadb** [comment]
noticed that builds can fail weirdly if the git command isn't found on windows.  The fix is to ensure that all developers install git for windows with the installation mode that causes the windows PATH to point to git.

**Comment by dbadb** [comment]
and when I re-installed gitbash, i now get this:

Could not write standard input to Gradle Test Executor 1.
java.io.IOException: The pipe is being closed

and all tests fail, not just a couple (relating to installed hardward)

**Comment by pietroglyph** [comment]
I will try to get some time later this week to debug the Git integration on Windows issue, if it isn't already resolved by then. It's a little odd that it's popping up now, because we did the same thing last year and never had problems.

**Review by pietroglyph — CHANGES_REQUESTED** [review]
This looks fine, except for two things:
 1. Camden had a PR that changed `SensorModel` to do conversions for motors attached to things that are not drivetrain wheels. I just merged it on SpartroncicsLib, but it will need to be integrated here. I was planning to do this PR and merge Camden's at the same time, but you beat me to this PR (I've been a little busy lately; I appreciate you doing this, it makes things easier on me).
 2. Justice feels that moving away from the JitPack adds so many files that it makes the code confusingly large to beginners, and that the JitPack is the clear solution w.r.t. version control and sharing with other teams. I'm pretty ambivalent with this issue, and I see issues with the JitPack (as we discussed), but I think you should discuss this with him just to get buy-in.

Thanks!

**Comment by dbadb** [comment]
I disabled tests for now.  git fix was to just install it so that $PATH has git installed.
I'm going to merge this pull request since:
a. i've been waiting on this issue for 2 or more weeks
b. i'm happy to discuss with justice, but i'm disappointed that such a trivial thing has been lying in limbo for this long.

**Pull request merged**
